### ISSUE TITLE
Deploy the Apps Script from a Google account

### ISSUE THREAD

**Issue by brittanylau** [RagtagOpen/freefrom-map-backend#102]
We should sort out which Google account we would like the form submission backend to live on! This account would:
* own the Google Sheet (can duplicate [this spreadsheet](https://docs.google.com/spreadsheets/d/1tKcaWGBS4z0_GY9F612T73NjUIUVoLP5oMLBkpNEOoU/edit?usp=sharing))
* deploy the Apps Script
* be the "sender" of notification emails

It's also important that the maintainer(s) of the account can ensure that the app is authorized to their account (basically just don't revoke access).

**Comment by egiurleo** [comment]
This is definitely a question for @sarahgreen!

**Comment by sarahgreen** [comment]
@egiurleo @brittanylau We should probably have FreeFrom own the sheets, unless it will be a pain in the butt with development and maintenance. What do you think?

Btw – I created the sheets in our shared Google Drive but I can transfer the ownership as needed. Here they are:
[Share Your Policy Ideas](https://docs.google.com/spreadsheets/d/1nNeRt_HGHxSsV45XYDaJThBbeMcPPir13fTNMYBIxvI/edit)
[Partner with FreeFrom](https://docs.google.com/spreadsheets/d/1IH4k5CQFbQzegbIh-ORrNKG0NajHghU6Qx0MfmZXtmY/edit)
[Give Feedback](https://docs.google.com/spreadsheets/d/1SWesqdImHhcSUpVKJMXgHl7uHCLVQKa_Ei7dYgaJ_Dw/edit)
[Build Collective Survivor Power](https://docs.google.com/spreadsheets/d/1dPaAeoPB-UMyeF44ByrhXwKE4oro0fYvEh9aHEWKdUk/edit)

**Comment by brittanylau** [comment]
This has been deployed on a Google account made for the app! Message on slack for the deployment info 🙂
