### ISSUE TITLE
Each state gets a rank based on an overall point score

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-backend#121]
Although we are using five overall score labels, FreeFrom actually has a numeric point score for each state (and DC). These are listed [here](https://docs.google.com/spreadsheets/d/1yhlMh7lddVuEihgKGAAMGCE63FR3eIMcD315hyFiprA/edit?ts=603815e5#gid=0).

They would like us to display a "rank" for each state in the state list and hovercard, which is based on this point score. For example, California is 1st with 29 points, Illinois is 2nd with 27 points, and Virginia is 51st with 0 points.

The API should allow for the numeric score and/or the rank to be added for each state. That way we can display the rank on the frontend.

Note: in cases of a tie, we will say the states are tied for the highest rank – e.g. OR, NY, and DC are all tied for 3rd place.

**Comment by sarahgreen** [comment]
@egiurleo FYI

**Comment by egiurleo** [comment]
I'll handle this this weekend!

**Comment by egiurleo** [comment]
Closed with #124.
