### ISSUE TITLE
Add "quote" field to every state

### ISSUE THREAD

**Issue by sarahgreen** [RagtagOpen/freefrom-map-backend#127]
Each state will have a quote from an (anonymous) survivor. We should add a new field to the DB for each state's quote.

Note: either the quotes needs to be sent over from FreeFrom in order to complete this ticket, or a new ticket should be filed for filling in the quotes later.

![survivor quote](https://user-images.githubusercontent.com/6788487/111745658-2682dd00-884a-11eb-8fa5-00b4160c25eb.png)

**Comment by sarahgreen** [comment]
@egiurleo Is this something you might have time to tackle? It's adding a free-text field to every state, to store a quote from a survivor in that state. FreeFrom is working on getting the quotes to us, and there's a corresponding frontend change here: https://github.com/RagtagOpen/freefrom-map-frontend/issues/160.

**Comment by egiurleo** [comment]
@sarahgreen yup! Gonna do it this weekend!

**Comment by sarahgreen** [comment]
Here is the content for the survivor quotes feature. There are a few states that do not have quotes.

[Quotes Content for each state page .xlsx](https://github.com/RagtagOpen/freefrom-map-backend/files/6233959/Quotes.Content.for.each.state.page.xlsx)
