### ISSUE TITLE
Modify the GET /categories/id endpoint to accept with_criteria param

### ISSUE THREAD

**Issue by egiurleo** [RagtagOpen/freefrom-map-backend#39]
Currently, the `GET /categories/<id>` endpoint does not return any information about the category's criteria. Modify the endpoint to accept a `with_criteria` param, which will cause it to return information about the category's criteria.

**Comment by brittanylau** [comment]
@egiurleo do we know what kind of info about the criteria is needed? Should we just return all of the criterion fields?

**Comment by egiurleo** [comment]
Good questions!
1. Yes I was envisioning all the criteria -- that way we can use this request on the CMS to display all categories along with their criteria.
2. Yup false by default!
