### ISSUE TITLE
Fix Python style issues 😅

### ISSUE THREAD

**Issue by egiurleo** [RagtagOpen/freefrom-map-backend#56]
1. We should pick a set of standards for Python styles (or maybe a formatting tool that will do this for us automatically)
2. We should reformat the entire backend to match these standards

**Comment by brittanylau** [comment]
@egiurleo I can look into this! Did you have any preference for a particular style guide?

**Comment by egiurleo** [comment]
@brittanylau None at all as long as the styles are all consistent :)
